# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "shivaa-terragrunt-state"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "environments\\dev\\vpc/terraform.tfstate"
    region         = "ap-south-1"
  }
}
